[project]
name = "flame-openai-agent"
version = "0.1.0"
description = "Flame OpenAI Agent Example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "openai",
  "openai-agents",
  "flamepy",
]

[tool.uv.sources]
flamepy = { path = "/usr/local/flame/sdk/python" }
