[project]
name = "langchain-example"
version = "0.1.0"
description = "Langchain Example by Flame"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "flamepy",
  "langchain",
  "langchain_deepseek",
]

[tool.uv.sources]
flamepy = { path = "/usr/local/flame/sdk/python" }
